// AUTH
export const ADMIN_LOGIN  = 'ADMIN_LOGIN';
export const ADMIN_SIGNUP = 'ADMIN_SIGNUP'

// HOME SLIDER
export const ADD_HOME_SLIDER_IMAGE = 'ADD_HOME_SLIDER_IMAGE'
export const GET_HOME_SLIDER_IMAGES = 'GET_HOME_SLIDER_IMAGES'
export const DELETE_HOME_SLIDER_IMAGE = 'DELETE_HOME_SLIDER_IMAGE'

// MOVIE CATEGORIES
export const GET_MOVIE_CATEGORIES =  'GET_MOVIE_CATEGORIES'
export const ADD_MOVIE_CATEGORY = 'ADD_MOVIE_CATEGORY'
export const DELETE_MOVIE_CATEGORY = 'DELETE_MOVIE_CATEGORY'

// MOVIES
export const GET_MOVIES = 'GET_MOVIES'
export const ADD_MOVIE = 'ADD_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE';

// NEW MOVIES
export const GET_NEW_MOVIES = 'GET_NEW_MOVIES';
export const ADD_NEW_MOVIE = 'ADD_NEW_MOVIE';
export const DELETE_NEW_MOVIE = 'DELETE_NEW_MOVIE';

// SERIES
export const GET_SERIES = 'GET_SERIES';
export const ADD_SERIES = 'ADD_SERIES';
export const DELETE_SERIES = 'DELETE_SERIES';

// CHATS
export const GET_CHATS = 'GET_CHATS';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_FULL_CHAT = 'DELETE_FULL_CHAT';


